#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

grep -q 'docs/plans/PPP-<slug>/plan.md' "$ROOT/plugins/forge/skills/using-forge/SKILL.md"
grep -q 'NO PRODUCT-BEHAVIOR IMPLEMENTATION WITHOUT AN APPROVED SPEC' "$ROOT/plugins/forge/skills/using-forge/SKILL.md"
grep -q 'docs/specs/NNN-<slug>/view.html' "$ROOT/plugins/forge/skills/using-forge/SKILL.md"
grep -q 'docs/plans/PPP-<slug>/view.html' "$ROOT/.agent-extensions/maintaining-forge/skills/maintaining-forge/references/portability-rules.md"
! grep -q '| Plans | `.forge/plans/' "$ROOT/.agent-extensions/maintaining-forge/skills/maintaining-forge/references/portability-rules.md"
grep -q 'docs/research/' "$ROOT/README.md"
grep -q 'docs/debug/' "$ROOT/README.md"
grep -q 'Related Specs' "$ROOT/plugins/forge/skills/writing-plans/SKILL.md"
grep -q 'docs/plans/PPP-<slug>/plan.md' "$ROOT/plugins/forge/skills/writing-plans/SKILL.md"
grep -q '0 or more' "$ROOT/plugins/forge/skills/writing-plans/SKILL.md"
! grep -q 'same `NNN` as the spec' "$ROOT/plugins/forge/skills/writing-plans/SKILL.md"
! grep -q 'combined review path' "$ROOT/plugins/forge/skills/writing-plans/references/plan-visual-structure.md"
grep -q 'docs/plans/PPP-<slug>/plan.md' "$ROOT/plugins/forge/skills/executing-plans/SKILL.md"
grep -q 'Progress History' "$ROOT/plugins/forge/skills/executing-plans/SKILL.md"
! grep -q 'progress-NNN' "$ROOT/plugins/forge/skills/executing-plans/SKILL.md"
! grep -q 'combined Viewer' "$ROOT/plugins/forge/skills/executing-plans/SKILL.md"
grep -q '`fast` defaults to `root`' "$ROOT/plugins/forge/skills/executing-plans/references/adaptive-routing.md"
grep -q '`balanced` defaults to `subagent`' "$ROOT/plugins/forge/skills/executing-plans/references/adaptive-routing.md"
grep -q '`frontier` defaults to `root`' "$ROOT/plugins/forge/skills/executing-plans/references/adaptive-routing.md"
grep -q 'User execution preferences override these defaults' "$ROOT/plugins/forge/skills/executing-plans/references/adaptive-routing.md"
grep -q 'Do not ask the user to choose an execution mode' "$ROOT/plugins/forge/skills/executing-plans/SKILL.md"
grep -q 'creating-agent-extensions' "$ROOT/plugins/forge/skills/using-forge/SKILL.md"
grep -q '14 active user-execution skills plus 1 deprecated compatibility router' "$ROOT/README.md"
grep -q '| `creating-agent-extensions` |' "$ROOT/README.md"
grep -q 'Codex, Claude Code, and Antigravity' "$ROOT/.agent-extensions/maintaining-forge/skills/maintaining-forge/SKILL.md"
grep -q '.agent-extensions/' "$ROOT/.agent-extensions/maintaining-forge/skills/maintaining-forge/references/portability-rules.md"
grep -q 'python3 "$MANAGER" --help' "$ROOT/scripts/validate.sh"
grep -q 'docs/debug/' "$ROOT/plugins/forge/skills/systematic-debugging/SKILL.md"
grep -q 'docs/specs/NNN-<slug>/view.html' "$ROOT/plugins/forge/skills/spec-viewer/SKILL.md"
grep -q 'docs/plans/PPP-<slug>/view.html' "$ROOT/plugins/forge/skills/spec-viewer/SKILL.md"
! grep -q '| `combined`' "$ROOT/plugins/forge/skills/spec-viewer/SKILL.md"
grep -q '`unverified`' "$ROOT/plugins/forge/skills/spec-viewer/SKILL.md"
grep -q 'SUCCESSFUL BUILD ENDS GENERATION. NO POST-BUILD VIEWER QA.' "$ROOT/plugins/forge/skills/spec-viewer/SKILL.md"
grep -q 'Do not run `--check`' "$ROOT/plugins/forge/skills/spec-viewer/SKILL.md"
grep -q 'do not manually validate it' "$ROOT/plugins/forge/skills/spec-viewer/SKILL.md"
grep -q 'Do not add a post-build viewport or scroll verification step' "$ROOT/plugins/forge/skills/spec-viewer/references/content-patterns.md"
! grep -q 'Combined mode' "$ROOT/plugins/forge/skills/spec-viewer/references/content-patterns.md"
grep -q 'Building a browser application UI' "$ROOT/plugins/forge/skills/spec-viewer/SKILL.md"
grep -q 'Building a public website' "$ROOT/plugins/forge/skills/spec-viewer/SKILL.md"
grep -q 'Changing the Viewer shell' "$ROOT/plugins/forge/skills/spec-viewer/SKILL.md"
grep -q 'DO NOT DESIGN' "$ROOT/plugins/forge/skills/ui-design/SKILL.md"
grep -q 'The successful build command is sufficient evidence' "$ROOT/plugins/forge/skills/verifying-work/SKILL.md"
grep -q 'do not add source-count, hash, browser, or layout validation after generation' "$ROOT/plugins/forge/skills/writing-plans/SKILL.md"
grep -q 'needs no hash, browser, or layout check' "$ROOT/plugins/forge/skills/executing-plans/SKILL.md"
grep -q 'test-forge-artifact-contract.sh' "$ROOT/.github/workflows/validate.yml"
grep -q 'docs/plans/' "$ROOT/.agent-extensions/maintaining-forge/skills/maintaining-forge/SKILL.md"
grep -q 'superseded by docs/specs/002-lifecycle-review-viewer/spec.md' "$ROOT/docs/specs/2026-07-04-forge-plugin-design.md"

printf 'test-forge-artifact-contract: all checks passed\n'
